### ISSUE TITLE
 Pilatus

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/dodal#306] opened 2024-01-25 16:49 UTC
There should be an ophyd-async implementation of the pilatus detector in dodal. 

## Acceptance Criteria
* Pilatus detector class written
* Capable of configuring a pilatus for hardware or software triggered scans

**Comment by keithralphs** [comment] 2024-04-03 09:09
Duplicate of #406

**Closed by keithralphs** 2024-04-03 09:09 UTC
Labels: enhancement
